[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]

[lib]
name = "myrust"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.4"
features = ["extension-module"]

[dependencies]
